#!/bin/bash

# Source docker-machine env
eval $(docker-machine env local)

# Forward port 8080 webviz
./scripts/pf 8080 -e local

# Forward port 8080 rosbridge
./scripts/pf 9090 -e local

# Execute kinematics
docker-compose up kinematics